Inc 3
EgorKo25/DevOps-Track-Yandex pull request #5
Opened 2022-12-02 23:29 UTC by EgorKo25

2022-12-05 23:25 UTC, capsulated requested changes
Есть некоторые моменты по организации пакетов и структур. Тема абстрактная, но проследить стиль можно посмотрев исходники стандартных пакетов go, чтобы понять общую концепцию. Вообще, всегда нужно изучать исходники библиотек, которые используются - это полезная привычка.

Если понадобиться консультация - пиши, созвонимся 1-1, расскажу как лучше организовать пакеты на основе рекомендаций коммьюнити go [тут](https://go.dev/doc/effective_go) и [в частности тут](https://go.dev/doc/effective_go)

2022-12-05 23:25 UTC, capsulated commented on internal/AgentSupport/AgentFunctions/agent_utils.go
> +	metricList = make(map[string]*StorageSupport.Gauge)
По-хорошему, создать бы объект пакет для обработки метрик с объектом `MetricList` и требуемыми полями. В конструкторе передавать структуру текущего `MemStats` и методы для преобразования. С мапой неудобно работать с такими составными данными. Мапа удобна для перечислений, типа key=value, а у нас посложнее, так как разные типы

2022-12-05 23:25 UTC, capsulated commented on internal/AgentSupport/AgentFunctions/agent_utils.go
> +			log.Fatalln(err)
В этом месте приложение не упадёт? Тоесть, если не получилось отправить метрики, то в рантайме приложение упадёт. Такое только на этапе запуска допустимо

2022-12-05 23:25 UTC, capsulated commented on internal/AgentSupport/AgentFunctions/agent_utils.go
> +			log.Fatal(err)
Выше `log.Fatal(err)`, а тут `log.Fatalln(err)`

2022-12-05 23:25 UTC, capsulated commented on internal/AgentSupport/AgentFunctions/agent_utils.go
> +func MyMonitor() {
Монитор лучше создать тип (с мапами, а лучше со структурами состоянием текущего MemStat) и привязать методами для обработки к этому типу

2022-12-05 23:25 UTC, capsulated commented on internal/AgentSupport/AgentFunctions/agent_utils.go
> +	durConf.pollInterval = 2
Конфиг также, в отдельный пакет - стандартная практика. И передавать другим объектам в их конструкторы, к примеру:
```go
package storage

interface Storer {
     SaveLink(string) string
     GetLink(string) string
}

type Store struct {
     LinksList <ТипОбъектаДляХранения>
}

func NewStore(cfg *config) (*Store, error) { 
   // конфигурация хранилки ...
}
```

```go
package cmd

func main() {
    ...
    cfg := NewConfig() //

    store, err := NewStore(cfg) 
    if err ...
    
    router, err := NewRouter(cfg, store)
    if err ...
}
```

2022-12-05 23:25 UTC, capsulated commented on internal/AgentSupport/README.md
> +## Функции, которые реализованы:
`README.md` хорошая практика! 👍

2022-12-05 23:25 UTC, capsulated commented on internal/ServerSupport/handlers/handlers.go
> +func AddMetricToStorage(m StorageSupport.MemStats) http.HandlerFunc {
Функции лучше привязать к объекту, чтобы в параметры вызова функции не передавать зависимость. Зависимости передаются в конструкторы для гибкого управления зависимостями, дальнейшему развитию кода и удобного покрытия тестами

2022-12-06 17:16 UTC, EgorKo25 commented
Исправил все ваши замечания! Спасибо

2022-12-07 21:05 UTC, capsulated requested changes
Половина не исправлена:
- Имя файлов не все переименованы
- Про создании типа Monitor нет изменений и нет обоснования. Нужно что-то одно из этого: либо изменить код, либо обосновать выбранное решение. Вполне можно даже в комьюнити обсуждать замечания менторов
- Копирование мапы так и не обосновано
- Функции, которые нужно организовать в пакеты или объединить со структурами - также ничего не изменено и никакого коммента. Это обязательная история для написания интерфейсов/тестов - правильная объектная организация (концептуализация) в проекте

После исправлений, скорее всего, ещё нужно будет ещё смотреть, так как структура проекта поменяется

Нужно организовать сущности в проекте. Если этого не сделать, то дорабатывать и покрывать тестами, и в дальнейшем рефакторить - будет невозможно

2022-12-07 21:05 UTC, capsulated commented on internal/storage/MemStatRule.go
> +func CreateBaseStorage() *MemStats {
[Лучше](https://github.com/Konstantin8105/Effective_Go_RU#%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%8B-%D0%B8-%D1%81%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%BD%D1%8B%D0%B5-%D0%BB%D0%B8%D1%82%D0%B5%D1%80%D0%B0%D0%BB%D1%8B) New<ИмяВозвращаемогоЗначения>, так как это конструктор, в принципе

2022-12-07 21:05 UTC, capsulated commented on internal/storage/MemStatRule.go
> +type MemStatsRule interface {
Интерфейсы обычно в самом верху, перед тем, где они используются

2022-12-07 21:05 UTC, capsulated commented on internal/storage/MemStatRule.go
> +type MemStats struct {
`MemStats` имя, такое же, как и структуры в пакете `runtime`? Лучше изменить немного, или дополнить

2022-12-09 23:42 UTC, EgorKo25 commented on internal/agent/agent_utils.go
> +func metricPtrCreator(val storage.Gauge) *storage.Gauge {
Все спомогательные функции удалены мной в новом пул реквесте, т.к. решено недопонимание с заданием

2022-12-09 23:44 UTC, EgorKo25 commented on internal/agent/agent_utils.go
> +func MyMonitor() {
Создал структуру Monitor
у нее есть конструктор `NewMonitor(cfg *config)`
и метод `Run( )` , который ее запускает

2022-12-09 23:45 UTC, EgorKo25 commented on internal/server/handlers/handlers.go
> +	return func(w http.ResponseWriter, r *http.Request) {
Убрал обертку, теперь во всех обработчиках тип возвращаемого значения `func(w http.ResponseWriter, r *http.Request)`

2022-12-09 23:55 UTC, EgorKo25 commented on internal/storage/MemStatRule.go
> +func CreateBaseStorage() *MemStats {
Исправил

2022-12-09 23:56 UTC, EgorKo25 commented on internal/storage/MemStatRule.go
> +type MemStatsRule interface {
Исправил

2022-12-09 23:56 UTC, EgorKo25 commented on internal/storage/MemStatRule.go
> +type MemStats struct {
Переименова в 'MetricStorage'

2022-12-13 04:02 UTC, capsulated approved these changes
Много ещё что исправить нужно. 

Сделаем так: я апрувлю и принимаю работу. Но перед следующим спринтом исправь, пожалуйста, новые комментарии, комить и пуш рабочую ветку - и присылай мне ссылку   на ветку (без PR). Я посмотрю, и создам ветку с комментариями, чтобы нагляднее было - с примерами. Пиши личным сообщением, как сделаешь. Не забудь: PR создавать не надо, на платформе отправлять на проверку также не нужно. Просто заранее скинешь - я посмотрю и напишу всё, а после этого - уже второй спринт реализовывать

2023-01-05 01:47 UTC, merged